<!-- <?php

$apiKey = "rzp_test_nGiglMc6737Bju";

?>
<script src="https://code.jquery.com/jquery-3.5.0.js"></script> -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<form><script src="https://checkout.razorpay.com/v1/payment-button.js" data-payment_button_id="pl_PHcHAOBSozIknp" async> </script> </form>
</body>
</html>
<!-- <form action="https://www.example.com/success/" method="POST">
    <script
       src="https://checkout.razorpay.com/v1/checkout.js"
        data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
        data-amount="29935" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
        data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
        data-order_id="order_CgmcjRh9ti2lP7"// Replace with the order_id generated by you in the backend.
        data-buttontext="Pay with Razorpay"
        data-name="Acme Corp"
        data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
        data-image="https://example.com/your_logo.jpg"
        data-prefill.name="Gaurav Kumar"
        data-prefill.email="gaurav.kumar@example.com"
        data-theme.color="#F37254"
    ></script>
    <input type="hidden" custom="Hidden Element" name="hidden"/>
    </form> -->